services:
  - type: web
    name: sidflix
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: SIDFLIX_REGION
        value: IN
